version: '3'
services:
    mariadb:
        container_name: esqueleto-mariadb
        image: mariadb:latest
        environment:
            - MYSQL_ROOT_PASSWORD=F14WeaG1BLKAnvIT7
            - MYSQL_DATABASE=esqueleto
    mssql:
        container_name: esqueleto-mssql
        image: mcr.microsoft.com/mssql/server:latest
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=F14WeaG1BLKAnvIT7
    mysql:
        container_name: esqueleto-mysql
        image: mysql:latest
        environment:
            - MYSQL_ROOT_PASSWORD=F14WeaG1BLKAnvIT7
            - MYSQL_DATABASE=esqueleto
    postgres:
        container_name: esqueleto-postgres
        image: postgres:latest
        environment:
            - POSTGRES_PASSWORD=F14WeaG1BLKAnvIT7
            - POSTGRES_DB=esqueleto
    application:
        container_name: esqueleto-application
        image: esqueleto-testing-jar:latest
        depends_on:
            - mariadb
            - mssql
            - mysql
            - postgres
